package model.entity;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Aug 30 10:47:11 BDT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ZipperDetailsEOImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        Detailid {
            public Object get(ZipperDetailsEOImpl obj) {
                return obj.getDetailid();
            }

            public void put(ZipperDetailsEOImpl obj, Object value) {
                obj.setDetailid((Number)value);
            }
        }
        ,
        Lineid {
            public Object get(ZipperDetailsEOImpl obj) {
                return obj.getLineid();
            }

            public void put(ZipperDetailsEOImpl obj, Object value) {
                obj.setLineid((Number)value);
            }
        }
        ,
        Gmtsize {
            public Object get(ZipperDetailsEOImpl obj) {
                return obj.getGmtsize();
            }

            public void put(ZipperDetailsEOImpl obj, Object value) {
                obj.setGmtsize((String)value);
            }
        }
        ,
        Zippersize {
            public Object get(ZipperDetailsEOImpl obj) {
                return obj.getZippersize();
            }

            public void put(ZipperDetailsEOImpl obj, Object value) {
                obj.setZippersize((String)value);
            }
        }
        ,
        ZipperLineEO {
            public Object get(ZipperDetailsEOImpl obj) {
                return obj.getZipperLineEO();
            }

            public void put(ZipperDetailsEOImpl obj, Object value) {
                obj.setZipperLineEO((ZipperLineEOImpl)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(ZipperDetailsEOImpl object);

        public abstract void put(ZipperDetailsEOImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int DETAILID = AttributesEnum.Detailid.index();
    public static final int LINEID = AttributesEnum.Lineid.index();
    public static final int GMTSIZE = AttributesEnum.Gmtsize.index();
    public static final int ZIPPERSIZE = AttributesEnum.Zippersize.index();
    public static final int ZIPPERLINEEO = AttributesEnum.ZipperLineEO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ZipperDetailsEOImpl() {
    }

    /**
     * Gets the attribute value for Detailid, using the alias name Detailid.
     * @return the Detailid
     */
    public Number getDetailid() {
        return (Number)getAttributeInternal(DETAILID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Detailid.
     * @param value value to set the Detailid
     */
    public void setDetailid(Number value) {
        setAttributeInternal(DETAILID, value);
    }

    /**
     * Gets the attribute value for Lineid, using the alias name Lineid.
     * @return the Lineid
     */
    public Number getLineid() {
        return (Number)getAttributeInternal(LINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Lineid.
     * @param value value to set the Lineid
     */
    public void setLineid(Number value) {
        setAttributeInternal(LINEID, value);
    }

    /**
     * Gets the attribute value for Gmtsize, using the alias name Gmtsize.
     * @return the Gmtsize
     */
    public String getGmtsize() {
        return (String)getAttributeInternal(GMTSIZE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Gmtsize.
     * @param value value to set the Gmtsize
     */
    public void setGmtsize(String value) {
        setAttributeInternal(GMTSIZE, value);
    }

    /**
     * Gets the attribute value for Zippersize, using the alias name Zippersize.
     * @return the Zippersize
     */
    public String getZippersize() {
        return (String)getAttributeInternal(ZIPPERSIZE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Zippersize.
     * @param value value to set the Zippersize
     */
    public void setZippersize(String value) {
        setAttributeInternal(ZIPPERSIZE, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity ZipperLineEOImpl.
     */
    public ZipperLineEOImpl getZipperLineEO() {
        return (ZipperLineEOImpl)getAttributeInternal(ZIPPERLINEEO);
    }

    /**
     * Sets <code>value</code> as the associated entity ZipperLineEOImpl.
     */
    public void setZipperLineEO(ZipperLineEOImpl value) {
        setAttributeInternal(ZIPPERLINEEO, value);
    }

    /**
     * @param detailid key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number detailid) {
        return new Key(new Object[]{detailid});
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("model.entity.ZipperDetailsEO");
        }
        return mDefinitionObject;
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        oracle.jbo.server.SequenceImpl s =new oracle.jbo.server.SequenceImpl("MJ_OM_ZIPPER_DETAIL_SEQ",getDBTransaction());
        oracle.jbo.domain.Number sVal = s.getSequenceNumber();
        setDetailid(sVal);

    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        super.doDML(operation, e);
    }
}
